[build-system]
requires = ["setuptools>=75"]
build-backend = "setuptools.build_meta"

[project]
name = "mpc-sample-toolkit"
version = "0.1.0a1"
description = "Open-source toolkit for creating, inspecting, editing, and organizing projects for the Akai MPC Sample."
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }
authors = [
    { name = "Tarik Campos" }
]
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest>=8.0"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-ra"
